name: ci

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]

env:
  VALK_VERSION: "0.7.4"

jobs:
  test:
    name: "Test on linux-x64"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install vman
        run: |
          curl -fL -o vman.tar.gz https://files.valk-cdn.dev/releases/vman/vman-linux-x64.tar.gz
          mkdir -p "$HOME/vman"
          tar -xf vman.tar.gz -C "$HOME/vman"
          echo "$HOME/vman/bin" >> "$GITHUB_PATH"
          echo "$HOME/.vman/bin" >> "$GITHUB_PATH"

      - name: Install valk
        run: vman use "$VALK_VERSION"

      - name: Install SQLite
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev

      - name: Install the packages
        run: vman install

      - name: Start the cache
        run: make cache

      - name: Run the tests
        run: make test
